[package]
name = "signal-hook"
version = "0.1.2"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Unix signal handling"
documentation = "https://docs.rs/signal-hook"
repository = "https://github.com/vorner/signal-hook"
readme = "README.md"
keywords = ["signal", "unix", "daemon"]
license = "Apache-2.0/MIT"

[badges]
travis-ci = { repository = "vorner/signal-hook" }
maintenance = { status = "actively-developed" }

[features]
mio-support = ["mio", "mio-uds"]

[dependencies]
arc-swap = "~0.3"
libc = "~0.2"
mio = { version = "~0.6", optional = true }
mio-uds = { version = "~0.6", optional = true }

[dev-dependencies]
version-sync = "~0.5"

[package.metadata.docs.rs]
features = ["mio-support"]
