[package]
name = "signal-hook"
version = "0.1.7"
authors = ["Michal 'vorner' Vaner <vorner@vorner.cz>"]
description = "Unix signal handling"
documentation = "https://docs.rs/signal-hook"
repository = "https://github.com/vorner/signal-hook"
readme = "README.md"
keywords = ["signal", "unix", "daemon"]
license = "Apache-2.0/MIT"

[badges]
travis-ci = { repository = "vorner/signal-hook" }
maintenance = { status = "actively-developed" }

[features]
mio-support = ["mio", "mio-uds"]
tokio-support = ["futures", "mio-support", "tokio-reactor"]

[dependencies]
arc-swap = "~0.3.5"
libc = "~0.2"
futures = { version = "~0.1", optional = true }
mio = { version = "~0.6", optional = true }
mio-uds = { version = "~0.6", optional = true }
tokio-reactor = { version = "~0.1", optional = true }

[dev-dependencies]
version-sync = "~0.5"
tokio = "~0.1"

[package.metadata.docs.rs]
features = ["mio-support", "tokio-support"]
